<a href="https://colab.research.google.com/github/faruk17035/Deep-Learning-Models/blob/main/short_seq_classification_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
from keras.layers import Dense, Dropout, LSTM, Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import pandas as pd
import numpy as np

input_file = '/content/gdrive/MyDrive/input.csv'

In [3]:
def load_data(test_split = 0.2):
    print ('Loading data...')
    df = pd.read_csv(input_file)
    df['sequence'] = df['sequence'].apply(lambda x: [int(e) for e in x.split()])
    df = df.reindex(np.random.permutation(df.index))

    train_size = int(len(df) * (1 - test_split))

    X_train = df['sequence'].values[:train_size]
    y_train = np.array(df['target'].values[:train_size])
    X_test = np.array(df['sequence'].values[train_size:])
    y_test = np.array(df['target'].values[train_size:])

    return pad_sequences(X_train), y_train, pad_sequences(X_test), y_test

In [17]:
X_train

array([[2, 2, 3],
       [1, 2, 3],
       [2, 3, 4],
       [4, 2, 1],
       [2, 3, 1],
       [1, 2, 4],
       [2, 1, 3]], dtype=int32)

In [19]:
pad_sequences(X_train), y_train, pad_sequences(X_test), y_test

(array([[2, 2, 3],
        [1, 2, 3],
        [2, 3, 4],
        [4, 2, 1],
        [2, 3, 1],
        [1, 2, 4],
        [2, 1, 3]], dtype=int32),
 array([1, 1, 1, 0, 0, 1, 0]),
 array([[4, 3, 1],
        [3, 2, 1]], dtype=int32),
 array([0, 0]))

In [13]:
def create_model(input_length):
    print ('Creating model...')
    model = Sequential()
    model.add(Embedding(input_dim = 188, output_dim = 50, input_length = input_length))
    #model.add(LSTM(output_dim=256, activation='sigmoid', inner_activation='hard_sigmoid', return_sequences=True))
    model.add(LSTM(units=256, activation='sigmoid', return_sequences=True))
    model.add(Dropout(0.5))
    model.add(LSTM(units=256, activation='sigmoid'))
    model.add(Dropout(0.5))
    model.add(Dense(1, activation='sigmoid'))

    print ('Compiling...')
    model.compile(loss='binary_crossentropy',
                  optimizer='rmsprop',
                  metrics=['accuracy'])
    return model


In [14]:
len(X_train[0])

3

In [16]:
X_train, y_train, X_test, y_test = load_data()

model = create_model(len(X_train[0]))

print ('Fitting model...')
hist = model.fit(X_train, y_train, batch_size=64, epochs=10, validation_split = 0.1, verbose = 1)

score, acc = model.evaluate(X_test, y_test, batch_size=1)
print('Test score:', score)
print('Test accuracy:', acc)

Loading data...
Creating model...
Compiling...
Fitting model...
Epoch 1/10
1/1 [==============================] - 6s 6s/step - loss: 0.5608 - accuracy: 0.6667 - val_loss: 1.7937 - val_accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 53ms/step - loss: 0.7441 - accuracy: 0.6667 - val_loss: 1.0403 - val_accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 58ms/step - loss: 0.7091 - accuracy: 0.6667 - val_loss: 1.1118 - val_accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 47ms/step - loss: 0.5135 - accuracy: 0.6667 - val_loss: 0.9277 - val_accuracy: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 54ms/step - loss: 0.7885 - accuracy: 0.5000 - val_loss: 1.2555 - val_accuracy: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 50ms/step - loss: 0.7070 - accuracy: 0.6667 - val_loss: 1.1080 - val_accuracy: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 48ms/step - loss: 0.7966 - 